version: '3.8'

services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./src:/home/appuser/app/src
      - ./config:/home/appuser/app/config
      - ./prompts:/home/appuser/app/prompts
      - ./logs:/home/appuser/app/logs
      - ./run_worker.py:/home/appuser/app/run_worker.py
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - redis

  worker:
    build: .
    command: ["python", "run_worker.py"]
    volumes:
      - ./src:/home/appuser/app/src
      - ./config:/home/appuser/app/config
      - ./prompts:/home/appuser/app/prompts
      - ./logs:/home/appuser/app/logs
      - ./run_worker.py:/home/appuser/app/run_worker.py
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - redis