"""add_rag_models

Revision ID: 3950395dfef3
Revises: 1
Create Date: 2025-08-17 19:19:34.208012

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "3950395dfef3"
down_revision = "1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "collection",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "document_chunk",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("document_id", sa.Integer(), nullable=False),
        sa.Column("collection_id", sa.Integer(), nullable=False),
        sa.Column("chunk_text", sa.Text(), nullable=False),
        sa.Column("embedding", postgresql.VECTOR(dim=1536), nullable=True),
        sa.Column(
            "chunk_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["collection_id"],
            ["collection.id"],
        ),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["document.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_document_chunk_embedding",
        "document_chunk",
        ["embedding"],
        unique=False,
        postgresql_using="hnsw",
        postgresql_with={"m": 16, "ef_construction": 64},
    )
    op.add_column("document", sa.Column("collection_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "document", "collection", ["collection_id"], ["id"])
    op.add_column("job", sa.Column("job_type", sa.String(), nullable=True))
    op.add_column("job", sa.Column("document_id", sa.Integer(), nullable=True))
    op.add_column("job", sa.Column("collection_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "job", "collection", ["collection_id"], ["id"])
    op.create_foreign_key(None, "job", "document", ["document_id"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "job", type_="foreignkey")
    op.drop_constraint(None, "job", type_="foreignkey")
    op.drop_column("job", "collection_id")
    op.drop_column("job", "document_id")
    op.drop_column("job", "job_type")
    op.drop_constraint(None, "document", type_="foreignkey")
    op.drop_column("document", "collection_id")
    op.drop_index("ix_document_chunk_embedding", table_name="document_chunk")
    op.drop_table("document_chunk")
    op.drop_table("collection")
    # ### end Alembic commands ###
